#ifndef MICEWARS_GLOBAL_VARS_H
#define MICEWARS_GLOBAL_VARS_H

#define GREEN   0x95C355
#define BLUE    0x3885E7
#define MICE_WIDTH  25
#define MICE_HEIGHT 25

#define AMOUNT_OF_CHEESE_HOLES 18
#define RIVER_DIVIDER 7

#define MOUSE1_IMG "img/mouse.png"

#endif //MICEWARS_GLOBAL_VARS_H
